# Generated by Django 5.2.5 on 2025-08-31 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fortune', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fortune',
            name='fortune_user',
        ),
    ]
