# Generated by Django 5.2.5 on 2025-09-01 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fortune', '0002_remove_fortune_fortune_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fortune',
            old_name='fortune_poem',
            new_name='title',
        ),
    ]
